# Generated by Django 4.2.24 on 2025-10-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('appetiser', 'Appetiser'), ('dessert', 'Dessert'), ('brunch', 'Brunch'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
