# Generated by Django 4.2.24 on 2025-09-25 16:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_recipe_id', models.IntegerField(default=0, verbose_name='Spoonacular Recipe Id')),
                ('api_image_url', models.URLField(default='')),
                ('api_source_url', models.URLField(default='')),
                ('is_external', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('prep_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prep time')),
                ('prep_time_units', models.CharField(choices=[('min', 'Minutes'), ('hr', 'Hours'), ('day', 'Days')], default='min', max_length=10, verbose_name='Prep time units')),
                ('cook_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cooking time')),
                ('cook_time_units', models.CharField(choices=[('min', 'Minutes'), ('hr', 'Hours'), ('day', 'Days')], default='min', max_length=10, verbose_name='Cooking time units')),
                ('servings', models.IntegerField()),
                ('instructions', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('notes', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('user', 'title', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50, verbose_name='Ingredient')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('fl_oz', 'Fluid Ounces'), ('pt', 'Pints'), ('qt', 'Quarts'), ('gal', 'Gallons'), ('piece', 'Pieces'), ('item', 'Items'), ('can', 'Cans'), ('bottle', 'Bottles'), ('jar', 'Jars'), ('bag', 'Bags'), ('box', 'Boxes'), ('pack', 'Packs'), ('bunch', 'Bunches'), ('head', 'Heads'), ('clove', 'Cloves'), ('slice', 'Slices'), ('pinch', 'Pinches'), ('dash', 'Dashes'), ('drop', 'Drops'), ('serving', 'Servings'), ('portion', 'Portions')], default='piece', max_length=10)),
                ('notes', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.savedrecipe')),
            ],
            options={
                'ordering': ['ingredient_name'],
                'unique_together': {('recipe_id', 'ingredient_name')},
            },
        ),
    ]
