# Generated by Django 4.2.24 on 2025-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='original_name',
            field=models.CharField(default='', max_length=50, verbose_name='Full ingredient'),
        ),
    ]
