# Generated by Django 4.2.24 on 2025-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='original_name',
            field=models.CharField(default='', max_length=200, verbose_name='Full ingredient'),
        ),
    ]
