# Generated by Django 4.2.24 on 2025-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_name',
            field=models.CharField(max_length=200, verbose_name='Ingredient'),
        ),
    ]
