# Generated by Django 4.2.24 on 2025-10-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='metric_units',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('cup', 'Cups'), ('cups', 'Cups'), ('servings', 'Servings'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('fl_oz', 'Fluid Ounces'), ('pt', 'Pints'), ('qt', 'Quarts'), ('gal', 'Gallons'), ('piece', 'Pieces'), ('item', 'Items'), ('can', 'Cans'), ('bottle', 'Bottles'), ('jar', 'Jars'), ('bag', 'Bags'), ('box', 'Boxes'), ('pack', 'Packs'), ('bunch', 'Bunches'), ('head', 'Heads'), ('clove', 'Cloves'), ('slice', 'Slices'), ('pinch', 'Pinches'), ('dash', 'Dashes'), ('drop', 'Drops'), ('serving', 'Servings'), ('portion', 'Portions')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='units',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('cup', 'Cups'), ('cups', 'Cups'), ('servings', 'Servings'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('fl_oz', 'Fluid Ounces'), ('pt', 'Pints'), ('qt', 'Quarts'), ('gal', 'Gallons'), ('piece', 'Pieces'), ('item', 'Items'), ('can', 'Cans'), ('bottle', 'Bottles'), ('jar', 'Jars'), ('bag', 'Bags'), ('box', 'Boxes'), ('pack', 'Packs'), ('bunch', 'Bunches'), ('head', 'Heads'), ('clove', 'Cloves'), ('slice', 'Slices'), ('pinch', 'Pinches'), ('dash', 'Dashes'), ('drop', 'Drops'), ('serving', 'Servings'), ('portion', 'Portions')], default='piece', max_length=20),
        ),
    ]
