# Generated by Django 4.2.24 on 2025-09-18 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('fl_oz', 'Fluid Ounces'), ('pt', 'Pints'), ('qt', 'Quarts'), ('gal', 'Gallons'), ('piece', 'Pieces'), ('item', 'Items'), ('can', 'Cans'), ('bottle', 'Bottles'), ('jar', 'Jars'), ('bag', 'Bags'), ('box', 'Boxes'), ('pack', 'Packs'), ('bunch', 'Bunches'), ('head', 'Heads'), ('clove', 'Cloves'), ('slice', 'Slices'), ('pinch', 'Pinches'), ('dash', 'Dashes'), ('drop', 'Drops'), ('serving', 'Servings'), ('portion', 'Portions')], default='piece', max_length=20)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('spices', 'Spices & Seasonings'), ('condiments', 'Condiments & Sauces'), ('oils', 'Oils & Vinegars'), ('canned', 'Canned Goods'), ('frozen', 'Frozen Items'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('baking', 'Baking Supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
