# Generated by Django 4.2.24 on 2025-09-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('spices', 'Spices & Seasonings'), ('condiments', 'Condiments & Sauces'), ('oils', 'Oils & Vinegars'), ('canned', 'Canned Goods'), ('frozen', 'Frozen Items'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('baking', 'Baking Supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='pantry.category'),
        ),
    ]
