# Generated by Django 4.2.24 on 2025-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_category_alter_pantryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('spices', 'Spices & Seasonings'), ('condiments', 'Condiments & Sauces'), ('oils', 'Oils & Vinegars'), ('canned', 'Canned Goods'), ('frozen', 'Frozen Items'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('baking', 'Baking Supplies'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category'),
        ),
    ]
