# Generated by Django 4.2.24 on 2025-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Item'),
        ),
    ]
