# Generated by Django 4.2.24 on 2025-09-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_alter_pantryitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name']},
        ),
    ]
