# Generated by Django 4.2.24 on 2025-10-09 16:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_pantryitem_image_alter_pantryitem_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
