# Generated by Django 4.2.24 on 2025-10-06 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('cup', 'Cups'), ('cups', 'Cups'), ('servings', 'Servings'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('fl_oz', 'Fluid Ounces'), ('pt', 'Pints'), ('qt', 'Quarts'), ('gal', 'Gallons'), ('piece', 'Pieces'), ('item', 'Items'), ('can', 'Cans'), ('bottle', 'Bottles'), ('jar', 'Jars'), ('bag', 'Bags'), ('box', 'Boxes'), ('pack', 'Packs'), ('bunch', 'Bunches'), ('head', 'Heads'), ('clove', 'Cloves'), ('slice', 'Slices'), ('pinch', 'Pinches'), ('dash', 'Dashes'), ('drop', 'Drops'), ('serving', 'Servings'), ('portion', 'Portions')], default='piece', max_length=20)),
                ('notes', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
