# Generated by Django 4.2.24 on 2025-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
