# Generated by Django 4.2.24 on 2025-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppinglistitem_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-week_start_date']},
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='in_pantry',
            field=models.BooleanField(default=False),
        ),
    ]
