# Generated by Django 4.2.24 on 2025-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shoppinglist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
