# Generated by Django 4.2.24 on 2025-10-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_mealplanitem_meal_type'),
        ('shopping', '0004_shoppinglistitem_picked_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='meal_plan_items',
            field=models.ManyToManyField(blank=True, help_text='Meal plan items included in this shopping list', related_name='shopping_lists', to='meals.mealplanitem'),
        ),
    ]
